spring.application.name=jenkins-test

server.port=8080

#jwt.secret=6ca53df74b1e4c62a6e879d14e42a1e3qwe1234567zxcvbnmlkjh
#jwt.issuer=kbs
#jwt.access-token.expiration-ms=600000
#jwt.refresh-token.expiration-ms=86400000

spring.datasource.url=jdbc:postgresql://my_postgres:5432/mydb
#spring.datasource.url=jdbc:postgresql://localhost:5432/dev1
#spring.datasource.url=jdbc:postgresql://192.168.1.9:5432/dev1
#spring.datasource.url=jdbc:postgresql://postgres-db:5432/dev1
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/dev1
spring.datasource.username=postgres
spring.datasource.password=P0$tGre$

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true